In [7]:
# Numpy = Numerical Python
# Defination = It is a Fundamental Package of Scientific computing in Python
# Array = An Array is Defines as collection of items that are stored at contiguous Memory Location
# Array's are not comma seperated

In [2]:
import numpy as np 

In [5]:
a1 = [10,20,30]
a2 = [20,40,60]
print(a1+a2)

[10, 20, 30, 20, 40, 60]


In [8]:
x = np.array([10,20,30])
y = np.array([20,40,60])
print(x)

[10 20 30]


In [23]:
ab = np.array([10,20,30,40,50])
print(ab)
print(ab[3:])

[10 20 30 40 50]
[40 50]


In [24]:
# # Functions in Nympy
# a.shape - Array Dimensions
# len(a) - Length of Array
# a.ndim -  number of array elements
# a.size = Number of array elements
# a.dtype = Data type of array elements
# a.astype() = Convert on array to a different type 


In [31]:
a = [10,20,30,40,50]
arr = np.array(a)
print(arr)
print(arr.shape)
print(len(arr))
print(arr.ndim)
print(arr.size)
print(arr.dtype)
print(arr.astype(float))

[10 20 30 40 50]
(5,)
5
1
5
int32
[10. 20. 30. 40. 50.]


In [39]:
b = [[10,20,30],[40,50,60]]
ar = np.array(b)
print(ar)
print(ar.shape) # rows & columns
print(len(ar))
print(ar.dtype)
print(ar.ndim)
print(ar.size) # total size of element


[[10 20 30]
 [40 50 60]]
(2, 3)
2
int32
2
6


In [40]:
# # # Mathematical operations and Funcations in Arrays
# # np.subtract(x,y)
# # np.add(x,y)
# # np.divide(x,y)
# np.multiply(x,y)
# np.exp(x)
# np.sqrt(x)
# np.pow(x)

In [48]:
print(x)
print(y)
print(np.add(x,y))
print(np.subtract(x,y))
print(np.multiply(x,y))
print(np.divide(x,y))
print(np.pow())

[10 20 30]
[20 40 60]
[30 60 90]
[-10 -20 -30]
[ 200  800 1800]
[0.5 0.5 0.5]


In [53]:
print(x)
print(y)
print(np.concatenate([x,y], axis = 0))

[10 20 30]
[20 40 60]
[10 20 30 20 40 60]


In [54]:
x1 = np.array([[1,2,3], [5,6,7]])
y1 = np.array([[10,20,30], [90,80,70]])
print(x1)
print(y1)

[[1 2 3]
 [5 6 7]]
[[10 20 30]
 [90 80 70]]


In [56]:
print(np.concatenate([x1,y1],axis = 0))

[[ 1  2  3]
 [ 5  6  7]
 [10 20 30]
 [90 80 70]]


In [59]:
print(np.concatenate([x1,y1],axis = 1))

[[ 1  2  3 10 20 30]
 [ 5  6  7 90 80 70]]


In [57]:
print(np.hstack([x1,y1]))

[[ 1  2  3 10 20 30]
 [ 5  6  7 90 80 70]]


In [58]:
print(np.vstack([x1,y1]))

[[ 1  2  3]
 [ 5  6  7]
 [10 20 30]
 [90 80 70]]


In [67]:
ab = np.array([1,2,3,4,5])
print(ab)
print(np.array_split(a,3))

[1 2 3 4 5]
[array([10, 20]), array([30, 40]), array([50])]


In [68]:
# np.append(a,b) - Append items to an array
# np.insert(a,1,5) - Inserts items in an array
# np.delete(a,[1]) - Delete items from an array

In [74]:
z = np.array([1,2,3])
w = np.array([9,8,7])
print(z)
print(w)
print(np.append(z,[4,5]))
print(np.insert(a,0,0))

[1 2 3]
[9 8 7]
[1 2 3 4 5]
[ 0 10 20 30 40 50]


In [80]:
z1 = np.array([[1,2],[99,98]])
# print(z1)
print(np.insert(z1,1,[22,33], axis = 0))

[[ 1  2]
 [22 33]
 [99 98]]


In [87]:
print(z1)
print()
print(np.delete(z1,1,axis = 1))

[[ 1  2]
 [99 98]]

[[ 1]
 [99]]


In [102]:
ab = np.array([5,4,3,2,1])
aa  = np.sort(ab)
print(ab)
print(aa)
print()
print(np.sort(ab))
print(np.where(ab % 2 == 0 ))
print(np.searchsorted(aa,3))

[5 4 3 2 1]
[1 2 3 4 5]

[1 2 3 4 5]
(array([1, 3], dtype=int64),)
2


In [110]:
print(ab)
print(np.sum(ab))
print(np.min(ab))
print(np.max(ab))
print(np.size(ab)) # total number of elements in "ab" array
print(np.mean(ab)) #Mean
print(np.cumsum(ab)) #Cummulative sum 
print(np.cumprod(ab))  #Cummulative Product 

[5 4 3 2 1]
15
1
5
5
3.0
[ 5  9 12 14 15]
[  5  20  60 120 120]


In [121]:
Price = np.array([10,20,30])
Quantity = np.array([90,80,70])
print(Price ,"\n", Quantity) #"\n" used this to print output in Next row
print()
print(np.cumprod([Price , Quantity], axis  = 0))

[10 20 30] 
 [90 80 70]

[[  10   20   30]
 [ 900 1600 2100]]


In [125]:
import statistics as sts

In [133]:
marks = np.array([10,15,20,30,35,40,50])
print(marks)
print()
print(np.mean(marks)) #sum of all the Values / Number of Values
print(np.median(marks)) # Centeral value after sorting
print(sts.mode(marks))
print(np.std(marks))
print(np.var(marks))

[10 15 20 30 35 40 50]

28.571428571428573
30.0
10
13.286482312670197
176.53061224489798
